###
GET  http://localhost:3000/users

###
DELETE http://localhost:3000/users/1  

###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "email": "igorgiovane67@gmail.com",
    "password": "123igor"
}

# ANIMES

### Retornar animes do banco
GET http://localhost:3000/animes

### Inserir animes no banco
POST http://localhost:3000/animes
Content-Type: application/json

{
    "name": "Kimetsu no Yaiba",
    "seasons": 2,
    "episodes": 37,
    "synopsis": "texto",
    "image_url": "url",
    "small_image_url": "url",
    "genres": "texto"
}

###
POST http://localhost:3000/animes
Content-Type: application/json

{
    "name": "Fullmetal Alchemist",
    "seasons": 1,
    "episodes": 56,
    "synopsis": "texto",
    "image_url": "url",
    "small_image_url": "url",
    "genres": "texto"
}

###
PUT http://localhost:3000/animes/2
Content-Type: application/json

{
    "name": "Fullmetal Alchemist",
    "seasons": 1,
    "episodes": 51,
    "synopsis": "texto",
    "image_url": "https://cdn.myanimelist.net/images/anime/10/75815.jpg",
    "small_image_url": "https://cdn.myanimelist.net/images/anime/10/75815t.jpg",
    "genres": "texto"
}

### Deleta Anime
DELETE http://localhost:3000/animes/1