###
GET  http://localhost:3000/users

###
DELETE http://localhost:3000/users/1  

###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "email": "igorgiovane67@gmail.com",
    "password": "123igor"
}

# ANIMES

### Retornar animes do banco
GET http://localhost:3000/animes

### Inserir animes no banco
POST http://localhost:3000/animes
Content-Type: application/json

{
    "name": "Jujutso Kaisen",
    "seasons": 1,
    "episodes": 24,
    "synopsis": "Sofrimento, arrependimento, vergonha: os sentimentos negativos dos humanos tornam-se Maldições, causando terríveis acidentes que podem levar até mesmo à morte. E pra piorar, Maldições só podem ser exorcizadas por outras Maldições. Certo dia, para salvar amigos que estavam sendo atacados por Maldições, Yuji Itadori engole o dedo do Ryomen-Sukuna, absorvendo sua Maldição. Ele então decide se matricular no Colégio Técnico de Feitiçaria de Tóquio, uma organização que combate as Maldições... e assim começa a heróica lenda do garoto que tornou-se uma Maldição para exorcizar uma Maldição.",
    "image_url": "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    "small_image_url": "https://cdn.myanimelist.net/images/anime/1171/109222t.jpg",
    "genres": "Exorcismo, terror"
}

### Atualização de Informações dos animes
PUT http://localhost:3000/animes/8
Content-Type: application/json

{
    "name": "Blue Exorcist",
    "seasons": 2,
    "episodes": 37,
    "synopsis": "A série segue sobre um adolescente chamado Rin Okumura que descobre que é filho de Satanás e está determinado a se tornar um exorcista, a fim de derrotá-lo depois da morte de seu tutor, o Padre Fujimoto.",
    "image_url": "https://cdn.myanimelist.net/images/anime/10/75195.jpg",
    "small_image_url": "https://cdn.myanimelist.net/images/anime/10/75195t.jpg",
    "genres": "Terror, Drama, Ação, Fantasia Sombria",
}

### Deleta Anime
DELETE http://localhost:3000/animes/1